using System.Collections.Generic;
using CodeNotion.Template.Data.SqlServer.Models.Interfaces;

namespace CodeNotion.Template.Data.SqlServer.Models;

public class MeshGroup : IEntity
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public ICollection<Mesh>? Meshes { get; set; }
    public string? Rules { get; set; }
    public bool AutoGenerated { get; set; }
    public IEnumerable<MeshGroupArticleRelation>? MeshGroupArticleRelations { get; set; }
}